### ISSUE TITLE
errors downloading the container

### ISSUE THREAD

**Issue by janetrbarclay** [amanzi/ats-short-course#8]
Hi - I'm getting the following error message when I try to download the container for the short course:

```
$ docker pull metsi/ats-short-course:latest
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=metsi%2Fats-short-course&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.
```

Does anyone have suggestions of what to try?

If I try to open Docker Desktop from the start menu, I get an error that access is denied because I'm not in the "docker-users" group. 

I'm working on a windows machine and just installed docker desktop this afternoon. 

I don't have administrative rights to my computer, but could reach out to our IT specialist if that is needed.

 
Thanks in advance for any suggestions!

PS I tried to post to the users group using the link from the email but got a message that the group doesn't exist or I don't have permission to post there

**Comment by jd-moulton** [comment]
Can you tell us what type of system you are on?  

And can you verify that docker is running? For example, what happens when you type
```
docker info
```
at the command line?

**Comment by janetrbarclay** [comment]
I'm on a windows laptop (running 64-bit windows 10 Enterprise ver 1909). I have the processor info if that would be helpful at all.

Here's the output of docker info:

![image](https://user-images.githubusercontent.com/3833808/131393339-6da0310b-b492-4daa-896f-4a03d1fab34f.png)

**Comment by jd-moulton** [comment]
It does look like docker is not running.  But you probably need to be in the docker-users group and/or get admin permissions so it would be best to get help from whomever administers your computer. 

I'm not sure how it looks on windows by on mac there is a little docker icon that you can click on to get status, restart, etc. and run the docker desktop.   Is there a similar icon on your tool bar or something?

**Comment by janetrbarclay** [comment]
I don't see an icon (but I did uncheck the box to add a desktop icon, though that doesn't usually prevent icons in the system tray). 

Is the docker-users group something that is set-up within the windows users or once docker desktop is opened?

**Comment by janetrbarclay** [comment]
I just the info on how to add the docker-users group in the docker docs. I'll touch base with my IT person and let you know if this solves it.

https://docs.docker.com/desktop/faqs/#why-do-i-see-the-docker-desktop-access-denied-error-message-when-i-try-to-start-docker-desktop

**Comment by janetrbarclay** [comment]
Adding my windows user account to the docker-users group (following the instructions in the link above) largely solved the issue. The only addition thing I had to do (after installing WSL 2 as noted) was slightly modify the command to check the version (adding winpty at the beginning)

`winpty docker run -it --rm metsi/ats-short-course:latest ats --version`

Thanks for your help!!
